### ISSUE TITLE
Keyword results page links don't resolve

### ISSUE THREAD

**Issue by jchavarri** [redex/redex.github.io#12]
Repro:

- Click on a keyword on the home page
- Click on a package from the results

The url generated is something like `https://redex.github.io/keywords/benchmarking/packages/unpublished/glennsl/bs-benchmarkjs` which includes the `keywords/<keyword>` before `/packages` and it can't be resolved by the server.

**Comment by glennsl** [comment]
Thanks, I'm aware and have already fixed it, but not deployed it yet since I'm in the middle of a large refactor.

It's not just package links on keywords pages btw, but every package and keyword link on any page in a "subdirectory", because they're all using relative paths.

**Comment by glennsl** [comment]
Deployed and fixed! Thanks again :)
