### ISSUE TITLE
Type signature search

### ISSUE THREAD

**Issue by CharString** [redex/redex.github.io#55]
[Hoogle](https://hoogle.haskell.org/), [elm-search](https://klaftertief.github.io/elm-search/) and [Pursuit](https://pursuit.purescript.org/) support searching by type signature. Does something like that exist for ReScript packages?

**Comment by glennsl** [comment]
Not that I know of. Also, this isn't really meant for rescript either, although many packages will still work with it. I would recommend using https://rescript-lang.org/packages instead.
