### ISSUE TITLE
Unpublished version of package still appears on search results

### ISSUE THREAD

**Issue by jchavarri** [redex/redex.github.io#8]
Not sure why, when writing `bn.` on the search field, the unpublished version still appears (nit: with stars, the published item has no stars). I checked `sources.json` and only the published version is there.

When clicking on the unpublished item, I get a 404.

![image](https://user-images.githubusercontent.com/220424/34749919-6bfff552-f5a4-11e7-94c0-6361ba5a5450.png)

**Comment by glennsl** [comment]
Thanks! I've removed the unpublished version.

The update script doesn't delete anything in the search index, so I have to do it manually. Which I sometimes forget.

The lack of stars comes from [npms](https://api.npms.io/v2/package/bs-bn.js). Not entrirely sure why, but perhaps the current version was published before there were any stars?
